#! /bin/sh

pgrep -x sxhkd > /dev/null || sxhkd &

bspc monitor -d      

bspc config border_width         2
bspc config window_gap          10

bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true


bspc config normal_border_color     "#708090"
bspc config focused_border_color    "#bac2de"
bspc config presel_border_color     "#575b75"

# start
sxhkd &
picom --config ~/.config/picom/picom.conf &
feh &
polybar &
dunst &


# keyboard layout
setxkbmap -option grp:alt_shift_toggle us,ara

# background
feh --bg-fill /home/islam/Downloads/lofi_cat.png

# mouse
bspc config pointer_modifier mod4
bspc config pointer_action1 move
bspc config pointer_action2 resize_side
bspc config pointer_action2 resize_corner
